export type Difficulty = 'easy'|'medium'|'hard';
export const categories = ['math','logic','riddles','science','trivia'] as const;
export type Category = typeof categories[number];
export type Puzzle = {category:Category;prompt:string;lines:string[];hint:string;answer:string};
const locales=['en','ar','es','fr','de','pt','it','nl','ru','tr','hi','ja','ko','zh','id','ur'];
// Each row is a complete localized question template, not an English fallback.
const texts = [
['Find the missing digit in each equation. Read your four digits from top to bottom.','Continue each sequence by one number. The last digit of each missing number forms your code, top to bottom.','I hide four digits in plain sight. Reverse the number below, then add the second number. Keep all four digits, including leading zeroes.','Four objects travel at constant speed. Distance = speed × time. Take the last digit of each distance in metres, from top to bottom.','Answer each clue. Read the four digits from top to bottom.','Work backwards using inverse operations. Each missing value is a single digit.','Find the repeated difference. Continue it once, then keep only the units digit.','Reverse all four digits first. Add only after reversing. Pad the result to four digits.','Multiply each pair. Only the units digit of each result belongs in your code.','Think of basic shapes, the calendar, and the natural world.','Sides of a triangle','Faces of a cube','Days in a week','Seasons in a year','Legs of an insect','Legs of a spider','Sides of a pentagon','Sides of a hexagon','Sides of an octagon'],
['أوجد الرقم الناقص في كل معادلة. اقرأ الأرقام الأربعة من الأعلى إلى الأسفل.','أكمل كل متتالية بعدد واحد. الرقم الأخير من كل عدد ناقص يشكل رمزك من الأعلى إلى الأسفل.','أخفي أربعة أرقام أمامك. اعكس العدد أدناه ثم أضف العدد الثاني. احتفظ بالأصفار البادئة.','تتحرك أربعة أجسام بسرعة ثابتة. المسافة = السرعة × الزمن. خذ الرقم الأخير من كل مسافة بالأمتار من الأعلى للأسفل.','أجب عن كل تلميح. اقرأ الأرقام من الأعلى للأسفل.','استخدم العمليات العكسية. كل قيمة ناقصة رقم واحد.','أوجد الفرق المتكرر ثم خذ رقم الآحاد للعدد التالي.','اعكس الأرقام الأربعة أولاً ثم اجمع. أكمل إلى أربعة أرقام بالأصفار.','اضرب كل زوج وخذ رقم الآحاد فقط.','فكر في الأشكال والتقويم والعالم الطبيعي.','أضلاع المثلث','أوجه المكعب','أيام الأسبوع','فصول السنة','أرجل الحشرة','أرجل العنكبوت','أضلاع الشكل الخماسي','أضلاع الشكل السداسي','أضلاع الشكل الثماني'],
['Encuentra el dígito que falta en cada ecuación. Lee de arriba abajo.','Continúa cada secuencia. El último dígito de cada número nuevo forma tu código, de arriba abajo.','Invierte el número de abajo y suma el segundo. Conserva cuatro dígitos, incluidos los ceros iniciales.','Cuatro objetos viajan a velocidad constante. Distancia = velocidad × tiempo. Toma el último dígito de cada distancia en metros.','Responde cada pista y lee los dígitos de arriba abajo.','Usa operaciones inversas. Cada valor es un solo dígito.','Encuentra la diferencia repetida y conserva las unidades.','Primero invierte los cuatro dígitos, luego suma. Añade ceros iniciales.','Multiplica cada par y conserva las unidades.','Piensa en formas, el calendario y la naturaleza.','Lados de un triángulo','Caras de un cubo','Días de una semana','Estaciones del año','Patas de un insecto','Patas de una araña','Lados de un pentágono','Lados de un hexágono','Lados de un octágono'],
['Trouvez le chiffre manquant dans chaque équation. Lisez de haut en bas.','Continuez chaque suite. Le dernier chiffre de chaque nouveau nombre forme le code, de haut en bas.','Inversez le nombre ci-dessous, puis ajoutez le second. Gardez quatre chiffres, y compris les zéros initiaux.','Quatre objets se déplacent à vitesse constante. Distance = vitesse × temps. Prenez le dernier chiffre de chaque distance en mètres.','Répondez aux indices et lisez les chiffres de haut en bas.','Utilisez les opérations inverses. Chaque valeur est un chiffre.','Trouvez la différence répétée et gardez les unités.','Inversez les quatre chiffres avant d’ajouter. Complétez avec des zéros.','Multipliez chaque paire et gardez les unités.','Pensez aux formes, au calendrier et à la nature.','Côtés d’un triangle','Faces d’un cube','Jours dans une semaine','Saisons dans une année','Pattes d’un insecte','Pattes d’une araignée','Côtés d’un pentagone','Côtés d’un hexagone','Côtés d’un octogone'],
['Finde die fehlende Ziffer jeder Gleichung. Lies von oben nach unten.','Setze jede Folge fort. Die letzte Ziffer jeder neuen Zahl ergibt den Code von oben nach unten.','Kehre die untere Zahl um und addiere die zweite. Behalte vier Ziffern einschließlich führender Nullen.','Vier Objekte bewegen sich gleichförmig. Strecke = Geschwindigkeit × Zeit. Nimm die letzte Ziffer jeder Strecke in Metern.','Beantworte die Hinweise und lies von oben nach unten.','Nutze Umkehroperationen. Jeder Wert ist einstellig.','Finde die konstante Differenz und behalte die Einerstelle.','Erst alle Ziffern umkehren, dann addieren. Mit Nullen auffüllen.','Multipliziere jedes Paar und behalte die Einerstelle.','Denke an Formen, Kalender und Natur.','Seiten eines Dreiecks','Flächen eines Würfels','Tage einer Woche','Jahreszeiten','Beine eines Insekts','Beine einer Spinne','Seiten eines Fünfecks','Seiten eines Sechsecks','Seiten eines Achtecks'],
['Ache o dígito ausente em cada equação. Leia de cima para baixo.','Continue cada sequência. O último dígito de cada novo número forma o código, de cima para baixo.','Inverta o número abaixo e some o segundo. Mantenha quatro dígitos, incluindo zeros iniciais.','Quatro objetos se movem a velocidade constante. Distância = velocidade × tempo. Use o último dígito de cada distância em metros.','Responda às pistas e leia de cima para baixo.','Use operações inversas. Cada valor é um dígito.','Ache a diferença repetida e guarde as unidades.','Inverta primeiro, depois some. Complete com zeros.','Multiplique os pares e guarde as unidades.','Pense em formas, calendário e natureza.','Lados de um triângulo','Faces de um cubo','Dias da semana','Estações do ano','Pernas de um inseto','Pernas de uma aranha','Lados de um pentágono','Lados de um hexágono','Lados de um octógono'],
['Trova la cifra mancante in ogni equazione. Leggi dall’alto in basso.','Continua ogni sequenza. L’ultima cifra di ogni nuovo numero forma il codice dall’alto in basso.','Inverti il numero qui sotto e aggiungi il secondo. Mantieni quattro cifre, inclusi gli zeri iniziali.','Quattro oggetti viaggiano a velocità costante. Distanza = velocità × tempo. Prendi l’ultima cifra di ogni distanza in metri.','Rispondi agli indizi dall’alto in basso.','Usa operazioni inverse. Ogni valore è una cifra.','Trova la differenza ripetuta e conserva le unità.','Inverti prima, poi somma. Completa con zeri.','Moltiplica le coppie e conserva le unità.','Pensa a forme, calendario e natura.','Lati di un triangolo','Facce di un cubo','Giorni in una settimana','Stagioni in un anno','Zampe di un insetto','Zampe di un ragno','Lati di un pentagono','Lati di un esagono','Lati di un ottagono'],
['Vind het ontbrekende cijfer in elke vergelijking. Lees van boven naar beneden.','Vervolg elke reeks. Het laatste cijfer van elk nieuw getal vormt je code van boven naar beneden.','Draai het getal om en tel het tweede erbij op. Houd vier cijfers, inclusief nullen vooraan.','Vier objecten bewegen met constante snelheid. Afstand = snelheid × tijd. Neem het laatste cijfer van elke afstand in meters.','Beantwoord de aanwijzingen van boven naar beneden.','Gebruik omgekeerde bewerkingen. Elke waarde is één cijfer.','Vind het vaste verschil en houd de eenheden.','Eerst omkeren, dan optellen. Vul aan met nullen.','Vermenigvuldig de paren en houd de eenheden.','Denk aan vormen, de kalender en de natuur.','Zijden van een driehoek','Vlakken van een kubus','Dagen in een week','Seizoenen per jaar','Poten van een insect','Poten van een spin','Zijden van een vijfhoek','Zijden van een zeshoek','Zijden van een achthoek'],
['Найдите пропущенную цифру в каждом уравнении. Читайте сверху вниз.','Продолжите каждую последовательность. Последняя цифра каждого нового числа образует код сверху вниз.','Переверните число ниже и прибавьте второе. Оставьте четыре цифры, включая нули в начале.','Четыре объекта движутся равномерно. Путь = скорость × время. Возьмите последнюю цифру каждого расстояния в метрах.','Ответьте на подсказки сверху вниз.','Используйте обратные операции. Каждое значение — одна цифра.','Найдите постоянную разность и оставьте единицы.','Сначала переверните, затем сложите. Дополните нулями.','Перемножьте пары и оставьте единицы.','Подумайте о фигурах, календаре и природе.','Стороны треугольника','Грани куба','Дни недели','Времена года','Ноги насекомого','Ноги паука','Стороны пятиугольника','Стороны шестиугольника','Стороны восьмиугольника'],
['Her denklemdeki eksik rakamı bul. Yukarıdan aşağıya oku.','Her diziyi devam ettir. Yeni sayıların son rakamları yukarıdan aşağıya kodu oluşturur.','Aşağıdaki sayıyı ters çevir ve ikinciyi ekle. Baştaki sıfırlar dahil dört rakam tut.','Dört cisim sabit hızla ilerler. Yol = hız × zaman. Metre cinsinden her yolun son rakamını al.','İpuçlarını yanıtla, yukarıdan aşağıya oku.','Ters işlemleri kullan. Her değer tek rakamdır.','Tekrarlanan farkı bul ve birler basamağını al.','Önce ters çevir, sonra topla. Sıfırlarla tamamla.','Çiftleri çarp ve birler basamağını al.','Şekilleri, takvimi ve doğayı düşün.','Üçgenin kenarları','Küpün yüzleri','Haftanın günleri','Yılın mevsimleri','Böceğin bacakları','Örümceğin bacakları','Beşgenin kenarları','Altıgenin kenarları','Sekizgenin kenarları'],
['हर समीकरण का लापता अंक खोजें। ऊपर से नीचे पढ़ें।','हर क्रम आगे बढ़ाएँ। हर नए अंक की इकाई आपके कोड का हिस्सा है, ऊपर से नीचे।','नीचे की संख्या उलटें, फिर दूसरी जोड़ें। शुरुआती शून्य सहित चार अंक रखें।','चार वस्तुएँ समान गति से चलती हैं। दूरी = गति × समय। मीटर में हर दूरी का इकाई अंक लें।','संकेतों के उत्तर ऊपर से नीचे पढ़ें।','उल्टी क्रियाएँ करें। हर मान एक अंक है।','स्थिर अंतर खोजें और इकाई अंक रखें।','पहले उलटें, फिर जोड़ें। शून्य लगाकर चार अंक बनाएँ।','हर जोड़े का गुणा करें और इकाई रखें।','आकृतियों, कैलेंडर और प्रकृति पर सोचें।','त्रिभुज की भुजाएँ','घन के फलक','सप्ताह के दिन','चार ऋतुओं वाले वर्ष की ऋतुएँ','कीट के पैर','मकड़ी के पैर','पंचभुज की भुजाएँ','षट्भुज की भुजाएँ','अष्टभुज की भुजाएँ'],
['各式の欠けた1桁を見つけ、上から順に並べてください。','各数列を1つ進めてください。新しい数の1の位を上から並べるとコードになります。','下の数字を逆順にし、2つ目の数を足してください。先頭の0を含め4桁にしてください。','4つの物体が一定の速さで移動します。距離＝速さ×時間。各距離のメートル値の1の位を上から並べてください。','各ヒントに答え、上から順に数字を並べてください。','逆算しましょう。空欄はそれぞれ1桁です。','一定の差を見つけ、次の数の1の位を残しましょう。','まず4桁を逆にしてから加算。0で4桁に揃えます。','各ペアを掛けて1の位を残しましょう。','図形、暦、自然を思い出しましょう。','三角形の辺の数','立方体の面の数','1週間の日数','四季の数','昆虫の脚の数','クモの脚の数','五角形の辺の数','六角形の辺の数','八角形の辺の数'],
['각 식에서 빠진 한 자리 숫자를 찾아 위에서 아래로 읽으세요.','각 수열을 하나씩 이어 보세요. 새 숫자의 일의 자리를 위에서 아래로 나열하면 코드가 돼요.','아래 숫자를 거꾸로 한 뒤 두 번째 수를 더하세요. 앞자리 0을 포함해 네 자리로 만드세요.','네 물체가 일정한 속력으로 이동해요. 거리 = 속력 × 시간. 각 거리의 미터 값에서 일의 자리를 위에서 아래로 나열하세요.','각 단서에 답하고 위에서 아래로 읽으세요.','역연산을 사용하세요. 각 값은 한 자리예요.','일정한 차이를 찾고 일의 자리만 남기세요.','먼저 뒤집고 더하세요. 0을 붙여 네 자리로 만드세요.','각 쌍을 곱하고 일의 자리만 남기세요.','도형, 달력, 자연을 생각해 보세요.','삼각형의 변 수','정육면체의 면 수','일주일의 날짜 수','사계절의 수','곤충의 다리 수','거미의 다리 수','오각형의 변 수','육각형의 변 수','팔각형의 변 수'],
['找出每个等式中缺少的一位数字，从上到下排列。','将每个数列延续一项。取每个新数字的个位，从上到下组成密码。','将下方数字倒序，再加上第二个数。保留四位，包括前导零。','四个物体匀速运动。路程＝速度×时间。取每个路程（米）的个位，从上到下排列。','回答每条线索，从上到下排列数字。','使用逆运算。每个空缺都是一位数字。','找到固定差值，延续一项，只保留个位。','先将四位数字倒序，再相加。用零补足四位。','将每对数相乘，只保留个位。','想想基本图形、日历与自然。','三角形的边数','正方体的面数','一周的天数','一年的季节数','昆虫的腿数','蜘蛛的腿数','五边形的边数','六边形的边数','八边形的边数'],
['Temukan digit yang hilang di setiap persamaan. Baca dari atas ke bawah.','Lanjutkan setiap deret. Digit terakhir setiap angka baru membentuk kode dari atas ke bawah.','Balik angka di bawah lalu tambahkan angka kedua. Pertahankan empat digit termasuk nol di depan.','Empat benda bergerak dengan kecepatan tetap. Jarak = kecepatan × waktu. Ambil digit terakhir tiap jarak dalam meter.','Jawab petunjuk dan baca dari atas ke bawah.','Gunakan operasi kebalikan. Setiap nilai satu digit.','Cari selisih tetap dan ambil satuannya.','Balik dulu lalu jumlahkan. Lengkapi dengan nol.','Kalikan tiap pasangan dan ambil satuannya.','Pikirkan bentuk, kalender, dan alam.','Sisi segitiga','Permukaan kubus','Hari dalam seminggu','Musim pada sistem empat musim','Kaki serangga','Kaki laba-laba','Sisi segi lima','Sisi segi enam','Sisi segi delapan'],
['ہر مساوات میں گمشدہ ہندسہ ڈھونڈیں۔ اوپر سے نیچے پڑھیں۔','ہر ترتیب کو آگے بڑھائیں۔ نئے عدد کا آخری ہندسہ کوڈ بناتا ہے۔','نیچے عدد الٹیں پھر دوسرا جمع کریں۔ شروع کے صفر سمیت چار ہندسے رکھیں۔','چار اجسام یکساں رفتار سے چلتے ہیں۔ فاصلہ = رفتار × وقت۔ ہر فاصلے کے میٹر کا آخری ہندسہ لیں۔','اشاروں کے جواب اوپر سے نیچے پڑھیں۔','الٹ عمل کریں۔ ہر قیمت ایک ہندسہ ہے۔','مستقل فرق تلاش کریں اور اکائی رکھیں۔','پہلے الٹیں پھر جمع کریں۔ صفر سے چار ہندسے مکمل کریں۔','ہر جوڑے کو ضرب دیں اور اکائی رکھیں۔','شکلوں، تقویم اور قدرت کے بارے میں سوچیں۔','مثلث کے ضلع','مکعب کے رخ','ہفتے کے دن','چار موسموں والے سال کے موسم','کیڑے کی ٹانگیں','مکڑی کی ٹانگیں','پانچ ضلع شکل کے ضلع','چھ ضلع شکل کے ضلع','آٹھ ضلع شکل کے ضلع']
];
export function makePuzzle(difficulty:Difficulty,level:number,locale='en',seed=0,forced?:Category):Puzzle {
 const li=Math.max(0,locales.indexOf(locale)); const s=texts[li];
 let state=(level*739+li*1709+({easy:1,medium:2,hard:3}[difficulty])*9311+seed)>>>0;
 const rand=(max:number)=> {state=(Math.imul(state,1664525)+1013904223)>>>0;return state%max;};
 const cat=forced || categories[(level-1)%5]; const di={easy:0,medium:1,hard:2}[difficulty]; const weight=level+di*35;
 let answer='',lines:string[]=[];
 if(cat==='math') {for(let i=0;i<4;i++){const digit=rand(10),a=2+rand(3)+weight,b=2+di+Math.floor(level/6); answer+=digit;lines.push(di===2?`(${a} + ?) × ${b} − ${level} = ${(a+digit)*b-level}`:di===1||level>15?`${a} + ? × ${b} = ${a+digit*b}`:`${a} + ? = ${a+digit}`);}}
 if(cat==='logic'){for(let i=0;i<4;i++){const a=rand(8)+weight,d=2+rand(4)+Math.floor(weight/5),factor=di===2?2:1;const nums=[a,a+d,a+d+d*factor,a+d+d*factor+d*factor*factor];const next=nums[3]+d*factor**3;answer+=next%10;lines.push(nums.join('   ·   ')+'   ·   ?');}}
 if(cat==='riddles'){let original=1000+rand(7000),reverse=Number(String(original).split('').reverse().join('')),add=10+weight+rand(300);if(reverse+add>9999)add=1;answer=String(reverse+add).padStart(4,'0');lines=[String(original),`+ ${add}`];}
 if(cat==='science'){for(let i=0;i<4;i++){const v=2+weight+rand(20),time=2+rand(7)+di*9;answer+=(v*time)%10;lines.push(`${v} m/s   ×   ${time} s   =   ? m`);}}
 if(cat==='trivia'){const values=[3,6,7,4,6,8,5,6,8];const used=new Set<number>();for(let i=0;i<4;i++){let n=rand(9);while(used.has(n))n=(n+1)%9;used.add(n); const shift=Math.min(2,di+Math.floor(level/15));lines.push(s[10+n]+(shift?` − ${shift}`:''));answer+=((values[n]-shift)%10+10)%10;}}
 let hint=s[5+categories.indexOf(cat)];if(cat==='logic'&&di===2)hint='× 2 → '+s[6];
 return {category:cat,prompt:s[categories.indexOf(cat)],lines,hint,answer};
}
