import type {Candidate, HintContext, Strategy, Strength} from './candidate.ts';
import {leaksCode} from './features.ts';

/**
 * Reasoning about a puzzle, exactly, before any model is involved.
 *
 * Every puzzle this app serves is generated by makePuzzle(), which means the shape of
 * every line is known and finite: an addition, a product, a subtraction, a four-term
 * arithmetic sequence, a reversal-and-add, a velocity-time product, or a named noun. That
 * is a closed set, and for a closed set arithmetic beats a language model. A hosted model
 * asked to hint at "3 + ? = 12" will sometimes answer 9; this layer cannot, because it
 * never guesses - it evaluates the line.
 *
 * What it will not do is state a digit of the code. The whole point of a hint is to
 * unblock a player, and a hint that finishes the puzzle is worse than no hint, so every
 * strategy here either describes a method or narrows the search without ever naming the
 * value it narrowed to. narrowFirstDigit() is the sharpest of them and is written to make
 * that structural rather than a matter of care: it emits a three-value window, so it
 * cannot degenerate into naming the digit even when the digit is at either end of the
 * range.
 *
 * Parsing is locale-independent on purpose. The generator writes digits and operators
 * into `lines` in every language and localises only the prompt, the canned hint and the
 * trivia nouns, so one set of patterns covers all sixteen locales.
 */

const MATH_HARD = /^\((\d+)\s*\+\s*\?\)\s*[×x*]\s*(\d+)\s*[−\-]\s*(\d+)\s*=\s*(\d+)\s*$/;
const MATH_MID = /^(\d+)\s*\+\s*\?\s*[×x*]\s*(\d+)\s*=\s*(\d+)\s*$/;
const MATH_EASY = /^(\d+)\s*\+\s*\?\s*=\s*(\d+)\s*$/;
const LOGIC_LINE = /^(\d+)\s*·\s*(\d+)\s*·\s*(\d+)\s*·\s*(\d+)\s*·\s*\??$/;
const SCIENCE_LINE = /^(\d+)\s*m\/s\s*[×x*]\s*(\d+)\s*s\s*=\s*\?\s*m$/;
const RIDDLE_ADD = /^\+\s*(\d+)\s*$/;
const TRIVIA_SHIFT = /[−-]\s*(\d+)\s*$/;

type MathShape = 'easy' | 'mid' | 'hard';

function mathShape(line: string): { shape: MathShape; a: number; b: number; c: number; r: number } | null {
  let m = MATH_HARD.exec(line);
  if (m) return { shape: 'hard', a: +m[1], b: +m[2], c: +m[3], r: +m[4] };
  m = MATH_MID.exec(line);
  if (m) return { shape: 'mid', a: +m[1], b: +m[2], c: 0, r: +m[3] };
  m = MATH_EASY.exec(line);
  if (m) return { shape: 'easy', a: +m[1], b: 1, c: 0, r: +m[2] };
  return null;
}

/** The hidden digit of a single math line, used only to build a window around it. */
function mathDigit(s: ReturnType<typeof mathShape>): number {
  if (!s) return 0;
  if (s.shape === 'hard') return Math.round((s.r + s.c) / s.b) - s.a;
  if (s.shape === 'mid') return (s.r - s.a) / s.b;
  return s.r - s.a;
}

/**
 * A three-value window that always contains the digit and is never only the digit.
 *
 * The offsets are chosen so the window slides rather than clamps: at the bottom it starts
 * at 0, at the top it ends at 9, and in every case it spans three values. A window that
 * collapsed to a single value at either end would hand over the answer exactly when the
 * answer was 0 or 9, which are the two digits a naive "centre it on the answer" version
 * gets wrong.
 */
export function digitWindow(digit: number): { lo: number; hi: number } {
  const d = Math.max(0, Math.min(9, Math.round(digit)));
  const lo = Math.max(0, Math.min(d - 1, 7));
  return { lo, hi: lo + 2 };
}

function push(out: Candidate[], c: Candidate) {
  // A candidate that states four digits in a row is not a hint. Dropping it here means
  // the network is never even offered one, so a leak cannot be ranked into first place.
  if (!c.text || leaksCode(c.text)) return;
  out.push(c);
}

const make = (
  strategy: Strategy,
  text: string,
  strength: Strength,
  specific: boolean,
): Candidate => ({ strategy, text, strength, specific });

/**
 * Every hint worth considering for this puzzle, in this language, unordered.
 *
 * The canned hint is always included and is the floor: it is stored with the puzzle, it is
 * already translated, and it cannot be wrong. If the model somehow scores everything else
 * below it, the player still gets a real hint rather than nothing.
 */
export function candidates(ctx: HintContext): Candidate[] {
  const { puzzle, difficulty, t } = ctx;
  const out: Candidate[] = [];
  const line = puzzle.lines[0] || '';

  // The stored hint, which is also the answer when nothing better survives.
  if (puzzle.hint) push(out, make('canned', puzzle.hint, 0, false));

  switch (puzzle.category) {
    case 'math': {
      const shape = mathShape(line);
      if (shape) {
        // Which operation to undo, worked out from the line rather than from the
        // difficulty: a hard line ends in a subtraction, so that is what comes off first.
        const key =
          shape.shape === 'hard' ? 'hintMathUndoHard'
          : shape.shape === 'mid' ? 'hintMathUndoMid'
          : 'hintMathUndoEasy';
        push(out, make('mathUndo', t(key), 1, true));

        if (shape.shape !== 'easy') {
          push(out, make('mathUnits', t('hintMathUnits'), 1, true));
        }
        const { lo, hi } = digitWindow(mathDigit(shape));
        push(out, make('mathNarrow', t('hintMathNarrow', { lo, hi }), 2, true));
      }
      break;
    }
    case 'logic': {
      const m = LOGIC_LINE.exec(line);
      const nums = m ? [m[1], m[2], m[3], m[4]].map(Number) : [];
      const gaps = nums.slice(1).map((n, i) => n - nums[i]);
      const constant = gaps.length === 3 && gaps[0] === gaps[1] && gaps[1] === gaps[2];
      if (m && constant) push(out, make('logicGap', t('hintLogicGap'), 1, true));
      // A hard sequence multiplies its step instead of repeating it, so the third gap is
      // the double of the first. Saying so is the whole hint; the gap itself stays hidden
      // because knowing it would hand over the digit.
      if (m && !constant) push(out, make('logicDouble', t('hintLogicDouble'), 2, true));
      break;
    }
    case 'riddles': {
      if (RIDDLE_ADD.test(puzzle.lines[1] || '')) {
        push(out, make('riddleOrder', t('hintRiddleOrder'), 1, true));
        push(out, make('riddlePad', t('hintRiddlePad'), 1, true));
      }
      break;
    }
    case 'science': {
      const m = SCIENCE_LINE.exec(line);
      if (m) {
        push(out, make('scienceFormula', t('hintScienceFormula'), 1, true));
        // Only offered when the distance is wide enough for the units digit to be a real
        // step rather than the whole number, which is what makes "keep the last digit"
        // advice rather than a restatement of the question.
        if (+m[1] * +m[2] >= 100) push(out, make('scienceFormula', t('hintScienceUnits'), 1, true));
      }
      break;
    }
    case 'trivia': {
      const shift = TRIVIA_SHIFT.exec(line);
      push(out, make('triviaDomain', t('hintTriviaDomain'), 1, true));
      if (shift) push(out, make('triviaDomain', t('hintTriviaShift', { n: +shift[1] }), 1, true));
      break;
    }
  }

  // A difficulty with nothing but the canned hint is still a difficulty with a hint, but
  // the model should be able to see that it is being asked to choose from one thing.
  if (difficulty === 'hard' && out.length === 1) {
    push(out, make('canned', t('hintStillWorthIt'), 0, false));
  }
  return out;
}
